search/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.search, name='search'),
 ]

softech_search/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('search.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

search/models.py
from django.db import models
from django.utils import timezone
import datetime


class Query(models.Model):
    """User Query Table"""
    query = models.CharField(max_length=250, unique=True)
    time = models.DateTimeField()

    def __str__(self):
        return self.query

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.time <= now

class Products(models.Model):
    """Table of data received from the softech.kg"""
    name = models.CharField(max_length=250)
    parametrs = models.TextField()
    price = models.IntegerField(default=0)
    url = models.TextField()
    query_id = models.ForeignKey(Query, on_delete=models.CASCADE)
    web_site=models.CharField(max_length=200)

    def __str__(self):
        return self.name

search/forms.py
from django import forms


class QueryForm(forms.Form):
    """Search form"""
    query = forms.CharField(max_length=100)

search/views.py
from django.shortcuts import render
from .forms import QueryForm
from search.services.softech.softech_main import SoftechMain
from search.services.myphone.myphone_main import MyphoneMain, ProductNotFound
from search.services.kivano.kivano_main import KivanoMain
from search.services.svetofor.svetofor_main import SvetovorMain


def search(request):
    if request.method == 'POST':
        form = QueryForm(request.POST)
        if form.is_valid():
            context = {
                'error': []
            }
            query = str(form.cleaned_data['query']).lower()
            """Вывод из myphone.kg"""
            try:
                myphone_result = MyphoneMain().myphonekg_main \
                    (user_query_name=query)
                context['myphone'] = myphone_result
            except ProductNotFound:
                context['error'].append(
                    {'myphone': "По запросу " + form.cleaned_data['query']
                                + " ничего не найдено"}
                )
            """Вывод из kivano.kg"""
            try:
                kivano_result = KivanoMain().kivano_main(user_query_name=query)
                context['kivano'] = kivano_result
            except:
                context['error'].append(
                    {'kivano': "По запросу " + form.cleaned_data['query']
                               + " ничего не найдено"})
            try:
                svetofor_result = SvetovorMain().svetofor_main \
                    (user_query_name=query)
                context['svetofor'] = svetofor_result
            except Exception:
                context['error'].append(
                    {'svetofor': "По запросу " + form.cleaned_data['query']
                                 + " ничего не найдено"})
            """Вывод из softech.kg"""
            try:
                softech_result = SoftechMain().softech_main \
                    (query=query)
                context['softech'] = softech_result
            except Exception:
                context['error'].append(
                    {'softech': "По запросу " + form.cleaned_data['query']
                                + " ничего не найдено"})
            return render(request, 'search/home.html', context)
        else:
            """Сделать ввывод ошибки в html"""
            error = form.errors
            return render(request, 'search/home.html', {'error': error})
    return render(request, 'search/home.html')

search/templates/search/home.html
<!--{% load static  %}-->
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Search Website</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
<main role="main">
    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">Search Products</h1>
            <p class="lead text-muted">Получите лучшие результаты по вашему запросу!</p>
            <form action='' method="post">
                <div class="d-flex justify-content-center">
                    <div class="input-group mb-3 col-6 mr-5">
                        {% csrf_token %}
                        <input class="form-control m-auto" type="text" name="query" maxlength="100" required=""
                               id="id_query">
                    </div>
                </div>
                <p class="mb-0">
                    <button type="submit" class="btn btn-primary">Поиск товаров</button>
                </p>
            </form>
        </div>
    </section>
    <div class="container">
        <h3 class="text-center mb-0 pb-4">Магазины</h3>
        <h4 class="text-center my-0 py-4">Myphone.kg</h4>
        {% if myphone %}
        <table class="table table-striped table-light">
            <tr>
                <th>Название</th>
                <th>Цена</th>
                <th>Параметры</th>
                <th>Ссылка</th>
            </tr>
            {% for product in myphone %}
            <tr>
                <td>{{ product.name }}</td>
                <td>{{ product.price }}</td>
                <td>{{ product.parametrs}}</td>
                <td><a type="button" href="{{ product.url }}"
                       class="btn btn-sm btn-outline-secondary px-2 my-auto ml-1">Подробнее</a>

            </tr>
            {% endfor %}
        </table>
        {% elif error %}
        {% for error in error %}
        <p class="text-center py-0 my-0">{{ error.myphone }}</p>
        {% endfor %}
        {% endif %}
        <h4 class="text-center my-0 py-4">Kivano.kg</h4>
        {% if kivano %}
        <table class="table table-striped table-light">
            <tr>
                <th>Название</th>
                <th>Цена</th>
                <th>Ссылка</th>
            </tr>
            {% for product3 in kivano %}
            <tr>
                <td>{{ product3.name }}</td>
                <td>{{ product3.price }}</td>
                <td><a type="button" href="{{ product3.url }}"
                       class="btn btn-sm btn-outline-secondary px-2 my-auto ml-1">Подробнее</a>

            </tr>
            {% endfor %}
        </table>
        {% elif error %}
        {% for error in error %}
        <p class="text-center py-0 my-0">{{ error.kivano }}</p>
        {% endfor %}
        {% endif %}
        <h4 class="text-center my-0 py-4">Svetofor.kg</h4>
        {% if svetofor %}
        <table class="table table-striped table-light">
            <tr>
                <th>Название</th>
                <th>Цена</th>
                <th>Ссылка</th>
            </tr>
            {% for product4 in svetofor %}
            <tr>
                <td>{{ product4.name }}</td>
                <td>{{ product4.price }}</td>
                <td><a type="button" href="{{ product4.url }}"
                       class="btn btn-sm btn-outline-secondary px-2 my-auto ml-1">Подробнее</a>

            </tr>
            {% endfor %}
        </table>
        {% elif error %}
        {% for error in error %}
        <p class="text-center py-0 my-0">{{ error.svetofor }}</p>
        {% endfor %}
        {% endif %}
        <h4 class="text-center my-0 py-4">Softech.kg</h4>
        {% if softech %}
        <table class="table table-striped table-light">
            <tr>
                <th>Название</th>
                <th>Цена</th>
                <th>Параметры</th>
                <th>Ссылка</th>
            </tr>
            {% for product2 in softech %}
            <tr>
                <td>{{ product2.name }}</td>
                <td>{{ product2.price }}</td>
                <td>{{ product2.parametrs}}</td>
               <td><a type="button" href="{{ product2.url }}"
               class="btn btn-sm btn-outline-secondary px-2 my-auto ml-1">Подробнее</a>
            </tr>
            {% endfor %}
        </table>
        {% elif error %}
        {% for error in error %}
        <p class="text-center py-0 my-0">{{ error.softech }}</p>
        {% endfor %}
        {% endif %}
    </div>
</main>
</body>
</html>